# Generated by Django 3.2.13 on 2022-06-04 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo', '0002_auto_20220603_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechauno', models.CharField(max_length=5000000)),
                ('tienda', models.CharField(max_length=5000000)),
                ('departamento', models.CharField(max_length=5000000)),
                ('vendedor', models.CharField(max_length=5000000)),
                ('producto', models.CharField(max_length=5000000)),
                ('valor', models.CharField(max_length=5000000)),
                ('fechados', models.CharField(max_length=5000000)),
                ('objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipo.descripcion')),
            ],
        ),
    ]
