# Generated by Django 3.2.13 on 2022-06-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='fechados',
            field=models.DateTimeField(max_length=5000000),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fechauno',
            field=models.DateTimeField(max_length=5000000),
        ),
    ]
