# Generated by Django 3.2.13 on 2022-06-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
