# Generated by Django 3.2.13 on 2022-06-04 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receta',
            new_name='Pedido',
        ),
    ]
